# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "1e534a3167a96bcbc8f239cfa61ae47d38f8e0cb"

[[deps.TEMPLATE]]
path = "."
uuid = "11111111-1111-1111-1111-111111111111"
version = "0.1.0"
